---

name: Check Commit Message

on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install fk-git-commit-msg-std
        run: |
          yarn config set registry https://registry.yarnpkg.com
          yarn add fk-git-commit-msg-std
      - name: Run fk-git-commit-msg-std
        env:
          COMMIT_MSG: ${{ toJson(github.event.commits.*.message) }}
        run: |
          node ./node_modules/fk-git-commit-msg-std/check.js -c "$PWD/.gitmsgrc.js" -e COMMIT_MSG
